alter table CLIENTS add column FOURNISSEUR_ID INTEGER;
alter table CLIENTS add constraint CLIENTS_REF_FOURNISSEURS 
	FOREIGN KEY(FOURNISSEUR_ID) REFERENCES FOURNISSEURS(ID);
	
alter table UTILISATEURS add column CLIENT_ID INTEGER;
alter table UTILISATEURS add constraint UTILISATEURS_REF_CLIENTS
	FOREIGN KEY(CLIENT_ID) REFERENCES CLIENTS(ID);